### ISSUE TITLE
When Ultimate Addons for Visual Composer is activated colors cannot be changed.

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/admin-color-bar#2] opened 2018-01-10 21:53 UTC
The following was submitted by a user:

HS ticket: https://secure.helpscout.net/conversation/470213866/194571/

Ok..so I created another local site using the same theme, Impreza, which comes packaged with WPBakery Page Builder and Ultimate Addons for Visual Composer plugins. Prior to activating those plugins I uploaded and activated imagify on it. The color bar settings worked fine. I then activated wpbakery page builder and still the admin colorbar settings worked fine. Then I activated ultimate addons for visual composer and thats when the colorbar settings became unresponsive. I triple checked this and it seems that the ultimate addons for visual composer is the culprit. I have attached 2 images, one before I activated ultimate addons and one after. You can see the difference. 

Before activating Ultimate Addons for Visual Composer plugin
![before-ultimate-addons](https://user-images.githubusercontent.com/1041421/34797530-7bc11c32-f60d-11e7-8cf4-18d78e8a90db.png)

After activating 
![afteractivating-ultimate-addons](https://user-images.githubusercontent.com/1041421/34797556-9b02efda-f60d-11e7-9a1e-77bd6bc808ef.png)
Ultimate Addons for Visual Composer plugin

**Comment by davejesch** [comment] 2018-01-11 01:37
@GreggFranklin Can you get a copy of this plugin? I need to reproduce this. Looks like they're adding some css/js to our settings page. I can probably fix by removing their stuff from our page, but I need to see the code to do that.

**Comment by GreggFranklin** [comment] 2018-01-11 02:08
I have asked for a copy of the plugin

**Comment by GreggFranklin** [comment] 2018-01-11 03:01
Here is a link to the plugin: https://www.dropbox.com/s/313bk4b966crdfm/Ultimate_VC_Addons.zip?dl=0

Let me know if you also need the Visual Composer plugin

**Comment by GreggFranklin** [comment] 2018-01-11 03:05
The client posted back the following: "One more thing. Evidently you have to have imagify active as well. When both plugins are active the colorbar settings will not work. Just an FYI"

https://wordpress.org/plugins/imagify/

**Comment by davejesch** [comment] 2018-01-11 04:55
Yes, please give me a link for Visual Composer, just in case. I want to make sure I'm working with the latest in the event I need it but it sounds like I only need Ultimate AddOns and Imagify. I bet both of those are just adding their css/js on all admin pages. Meh.

**Comment by GreggFranklin** [comment] 2018-01-11 05:18
I agree, but here is the link: https://www.dropbox.com/s/93j67m4hss0a57u/codecanyon-242431-visual-composer-page-builder-for-wordpress-wordpress-plugin.zip?dl=0

**Comment by davejesch** [comment] 2018-01-12 02:18
@GreggFranklin I have install VC, Ultimate Addons and Imagify. I do not see the behavior you've described. I think I need the theme as well.

**Comment by GreggFranklin** [comment] 2018-01-12 15:26
The client has recontacted me this morning and said:



Attached is the theme. Problem is in order to activate it I would have to give you my themeforest account login. This has to be done in order for you to be able to add the plugins that come with it. Yeah I know, Kind of crappy and they implemented that a year after I purchased it.

Anyways, there was an update to imagify that I applied yesterday and I was having the same problem but **when I loaded desktopserver this morning and took a look it was working fine**. I am thinking their update fixed the issue maybe?
1.6.14.1 – 2018/01/11

    Bug Fix: no more conflicts between our script used for the charts and theme builders, or plugins that use an outdated version of this script.

1.6.14 – 2018/01/10

    New: added compatibility with partners’ plugins.
    Improvement: updated the script used for the charts, it will lower the risk of conflicts with other plugins (that are also up-to-date).
    Improvement: the comparison tool button is now also inserted when clicking the next/previous buttons in the media modal.
    Bug Fix: the comparison tool button should not be inserted several times anymore.
    Bug Fix: the images wouldn’t appear in the comparison tool sometimes.

Provided theme: https://www.dropbox.com/s/vkyzyk81cv6xi4d/themeforest-6434280-impreza-retina-responsive-wordpress-theme-wordpress-theme.zip?dl=0

***But it sounds like we don't need to do anything, and we should close this ticket.  Let me know.

**Comment by davejesch** [comment] 2018-01-12 18:43
If he says it's working fine, then it looks like the plugin updates have resolved it. That probably explains why I couldn't see it either: I installed the plugin yesterday, which probably included the update. That, or it only occurs when the theme is active. Either way, if he's fine and it's working for him, I think we can close it.

**Closed as completed** 2018-01-12 19:38 UTC
Labels: bug
